// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8n0-bPXfzvfCb7isBaWyDuHC5jPXGEN8',
    appId: '1:982339964254:web:bbe9ca75ff8fb5c98dd3cf',
    messagingSenderId: '982339964254',
    projectId: 'smart-home1-c7725',
    authDomain: 'smart-home1-c7725.firebaseapp.com',
    databaseURL: 'https://smart-home1-c7725-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home1-c7725.firebasestorage.app',
    measurementId: 'G-XE863WE5TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2yUX4ZzCT1lYzUjOgeq4jm8gCObz-Lys',
    appId: '1:982339964254:android:e1c5c0f566e3dfee8dd3cf',
    messagingSenderId: '982339964254',
    projectId: 'smart-home1-c7725',
    databaseURL: 'https://smart-home1-c7725-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home1-c7725.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImlO9589TO3Ba9NCEK2gmCtKTe0oHbW0',
    appId: '1:982339964254:ios:ccee8978523b71408dd3cf',
    messagingSenderId: '982339964254',
    projectId: 'smart-home1-c7725',
    databaseURL: 'https://smart-home1-c7725-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home1-c7725.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBImlO9589TO3Ba9NCEK2gmCtKTe0oHbW0',
    appId: '1:982339964254:ios:ccee8978523b71408dd3cf',
    messagingSenderId: '982339964254',
    projectId: 'smart-home1-c7725',
    databaseURL: 'https://smart-home1-c7725-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home1-c7725.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8n0-bPXfzvfCb7isBaWyDuHC5jPXGEN8',
    appId: '1:982339964254:web:b1242da07bd17f7c8dd3cf',
    messagingSenderId: '982339964254',
    projectId: 'smart-home1-c7725',
    authDomain: 'smart-home1-c7725.firebaseapp.com',
    databaseURL: 'https://smart-home1-c7725-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home1-c7725.firebasestorage.app',
    measurementId: 'G-S3RFWYK7WY',
  );

}